# Generated by Django 5.0.2 on 2024-05-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_checkout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
    ]
