# Generated by Django 5.0.2 on 2024-05-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counseling',
            new_name='Counseling1',
        ),
    ]
