# Generated by Django 5.0.2 on 2024-05-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_counseling_counseling1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counseling1',
            new_name='Counseling',
        ),
    ]
