# Generated by Django 5.0.2 on 2024-05-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_counseling1_counseling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counseling',
            options={'verbose_name': 'مشاوره', 'verbose_name_plural': 'مشاوره ها'},
        ),
        migrations.AddField(
            model_name='counseling',
            name='is_counseling',
            field=models.BooleanField(default=False, verbose_name='تایید پاسخگویی'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='number',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
    ]
