# Generated by Django 5.0.2 on 2024-04-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30)),
                ('name2', models.CharField(max_length=30)),
                ('name3', models.CharField(max_length=30)),
                ('name4', models.CharField(max_length=30)),
                ('name5', models.CharField(max_length=30)),
                ('name6', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='images/photo')),
            ],
        ),
    ]
