# Generated by Django 5.0.2 on 2024-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
