# Generated by Django 5.0.2 on 2024-04-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_name_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='name1',
            new_name='name',
        ),
    ]
