# Generated by Django 5.0.2 on 2024-04-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_name_slug_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='name',
            new_name='name1',
        ),
    ]
