# Generated by Django 5.0.2 on 2024-04-25 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customer_product_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتری ها'},
        ),
        migrations.AlterModelOptions(
            name='manufacture',
            options={'verbose_name': 'سازنده', 'verbose_name_plural': 'سازنده ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='', verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default='', verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام سازنده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(to='shop.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='کپشن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='آیا این محصول تخفیف دارد؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.manufacture', verbose_name='نام سازنده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='images/photo/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', verbose_name='اسلاگ'),
        ),
    ]
