# Generated by Django 5.0.2 on 2024-04-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_name_logo_alter_name_name1_alter_name_name2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'verbose_name': 'اسم', 'verbose_name_plural': 'اسم ها'},
        ),
    ]
