# Generated by Django 5.0.2 on 2024-05-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
